export {default as Home} from '../pages/Home'
export {default as Cart} from '../pages/Cart'
export {default as Category} from '../pages/Category'
export {default as Login} from '../pages/Login'
export {default as Product} from '../pages/Product'
